# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sauce Pipline Browser Tests

on:
  pull_request:
  push:
    branches:
      - master

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  testrunner-job:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/sauce-puppeteer-runner:latest
         
    steps:
      # appears that checkout@v2 uses javascript which is not compatible 
      # with the included node version in the container image.
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Workaround for container permissions
        run: sudo chown -R $USER:$(id -gn $USER) /github/home
        
      - name: Run Sauce Pipeline Test
        run: |
          sudo apt-get install xvfb
          /home/testrunner/entry.sh &
          sleep 2
          xvfb-run --auto-servernum saucectl run -c ./.sauce/config.yml


