# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  testrunner-job:
    runs-on: ubuntu-latest
    
    services:
      testrunner:
        image: saucelabs/sauce-puppeteer-runner:latest
         
    steps:
      - uses: actions/checkout@v2
    
      - run: docker cp ./tests/demo.test.js testrunner:/home/testrunner/tests
      - run: docker exec testrunner saucectl run /home/testrunner/tests


