# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    container: saucelabs/sauce-puppeteer-runner:latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: sauce-test
    
    - name: Build and Test
      working-directory: sauce-test
      run: |
        ls -al
        npm install

