# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  testrunner-job:
    runs-on: ubuntu-latest
    container: saucelabs/sauce-puppeteer-runner:latest
         
    steps:
      # appears that checkout@v2 uses javascript which is not compatible 
      # with the included node version in the container image.
      - uses: actions/checkout@v1
      - run: ls -al
      - run: saucectl run ./tests/demo.test.js


