# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  testrunner-job:
    runs-on: ubuntu-latest
    container: saucelabs/sauce-puppeteer-runner:latest
         
    steps:   
      - run: node -v
      - run: npm -v
      - run: ls -al
      - run: pwd
      - uses: actions/checkout@v2
      - run: ls -al


